clone:
  depth: 1
pipelines:
  default:
    - step:
        image: cloudrexx/web:PHP7.0
        script:
          - mysql -uroot -pcloudrexx -e "SET @@SQL_MODE = CONCAT(@@SQL_MODE, ',NO_ENGINE_SUBSTITUTION');"
          - mysql -uroot -pcloudrexx < ./installer/dump/contrexx_dump_structure.sql
          - mysql -uroot -pcloudrexx < ./installer/dump/contrexx_dump_data.sql
          - ./cx wb test 2>&1
        services:
          - database
definitions:
  services:
    database:
      image: mariadb
      environment:
        MYSQL_ROOT_PASSWORD: 'cloudrexx'
        MYSQL_DATABASE: 'dev'